data:
  data_type: "image"
  data_path: "./data/cropped/"
  batch_size: 8
  train_split: 0.75
  image_size: 224
  normalize: False
  center_wrist: False
  num_classes: 3

hyper:
  model: "cnn"
  epochs: 15
  learning_rate: 0.05
  optimizer: "sgd"
  criterion: "CrossEntropyLoss"

device: "mps"

save_path: "./output/ic.pth"
