data:
  data_type: "landmark"
  data_path: "./landmark_data.pickle"
  batch_size: 16
  train_split: 0.75
  image_size: 224
  normalize: True
  center_wrist: False
  num_classes: 3

hyper:
  model: "ann"
  epochs: 20
  learning_rate: 0.05
  optimizer: "sgd"
  criterion: "CrossEntropyLoss"

device: "mps"

save_path: "./output/la.pth"
